name: PushToServer
run-name: ${{ github.actor }} is deploying to Skylab 🚀
on: 
  [push]:
    paths:
      - 'Overkoepelend/CSSHarris/**'
jobs:
  Deploy-On-Server:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - run: echo "🖥️ The workflow is now ready to deploy on the server."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Build .NET App
        run : |
        sudo apt-get update && \
          sudo apt-get install -y dotnet-sdk-7.0
        dotnet build

      - run: echo "🖥️ The workflow is now ready to update the database"
      - name: Update database
        run: |
          dotnet tool install --global dotnet-ef
          dotnet tool restore
          dotnet ef update-database

      - run: echo "🖥️ The workflow is now ready to publish the application."
      - name: Publish application
        run : dotnet publish -c Release -o publish/

      - run: echo "🖥️ The workflow is now ready to upload to server."
      - name: Copy files to server
        uses: labhatorian/cssharris@main
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        source: publish/
        target: ${{ env.REMOTE_DIRECTORY }}

      - run: echo "🍏 This job's status is ${{ job.status }}."