// <auto-generated />
using CijferRegistratie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CijferRegistratie.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230329164757_Pogingen")]
    partial class Pogingen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CijferRegistratie.Models.Poging", b =>
                {
                    b.Property<int>("PogingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PogingId"));

                    b.Property<int>("Jaar")
                        .HasColumnType("int");

                    b.Property<int>("Resultaat")
                        .HasColumnType("int");

                    b.Property<string>("VakNaam")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PogingId");

                    b.HasIndex("VakNaam");

                    b.ToTable("Pogingen");
                });

            modelBuilder.Entity("CijferRegistratie.Models.Vak", b =>
                {
                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EC")
                        .HasColumnType("int");

                    b.HasKey("Naam");

                    b.ToTable("Vakken");

                    b.HasData(
                        new
                        {
                            Naam = "Server",
                            EC = 4
                        },
                        new
                        {
                            Naam = "C#",
                            EC = 4
                        },
                        new
                        {
                            Naam = "Databases",
                            EC = 3
                        },
                        new
                        {
                            Naam = "UML",
                            EC = 3
                        },
                        new
                        {
                            Naam = "KBS",
                            EC = 9
                        });
                });

            modelBuilder.Entity("CijferRegistratie.Models.Poging", b =>
                {
                    b.HasOne("CijferRegistratie.Models.Vak", "Vak")
                        .WithMany("Pogingen")
                        .HasForeignKey("VakNaam");

                    b.Navigation("Vak");
                });

            modelBuilder.Entity("CijferRegistratie.Models.Vak", b =>
                {
                    b.Navigation("Pogingen");
                });
#pragma warning restore 612, 618
        }
    }
}
