// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TakenlijstManager.Data;

#nullable disable

namespace TakenlijstManager.Migrations
{
    [DbContext(typeof(TakenManagerDbContext))]
    [Migration("20230330075051_taakPrioriteit")]
    partial class taakPrioriteit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TakenlijstManager.Data.Entities.Taak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Omvang")
                        .HasColumnType("int");

                    b.Property<int>("Prioriteit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Taken");
                });
#pragma warning restore 612, 618
        }
    }
}
