# This workflow will build and test the ASP.NET CORE project MHeet.

name: Build and Test MHeet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./Overkoepelend/CSSHarris/CSSHarris/CSSHarris.csproj
      
    - name: Build project
      run: dotnet build --configuration Release --no-restore ./Overkoepelend/CSSHarris/CSSHarris/CSSHarris.csproj
  
  # Not finished yet
   # - name: Test
   #   run: dotnet test --no-restore --verbosity normal ./test/test.csproj
